# coding: utf-8

from __future__ import absolute_import
from openapi_server.models.text_person_name_annotation \
    import TextPersonNameAnnotation
from typing import List
from openapi_server.models.base_model_ import Model
from openapi_server import util


class TextPersonNameAnnotationResponse(Model):
    """NOTE: This class is auto generated by
    OpenAPI Generator (https://openapi-generator.tech).
    Do not edit the class manually.
    """

    def __init__(self, text_person_name_annotations=None):  # noqa: E501
        """TextPersonNameAnnotationResponse - a model defined in OpenAPI

        :param text_person_name_annotations: The text_person_name_annotations of this TextPersonNameAnnotationResponse.  # noqa: E501
        :type text_person_name_annotations: List[TextPersonNameAnnotation]
        """
        self.openapi_types = {
            'text_person_name_annotations': List[TextPersonNameAnnotation]
        }

        self.attribute_map = {
            'text_person_name_annotations': 'textPersonNameAnnotations'
        }

        self._text_person_name_annotations = text_person_name_annotations

    @classmethod
    def from_dict(cls, dikt) -> 'TextPersonNameAnnotationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextPersonNameAnnotationResponse of this TextPersonNameAnnotationResponse.  # noqa: E501
        :rtype: TextPersonNameAnnotationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text_person_name_annotations(self):
        """Gets the text_person_name_annotations of this TextPersonNameAnnotationResponse.

        A list of person name annotations  # noqa: E501

        :return: The text_person_name_annotations of this TextPersonNameAnnotationResponse.
        :rtype: List[TextPersonNameAnnotation]
        """
        return self._text_person_name_annotations

    @text_person_name_annotations.setter
    def text_person_name_annotations(self, text_person_name_annotations):
        """Sets the text_person_name_annotations of this TextPersonNameAnnotationResponse.

        A list of person name annotations  # noqa: E501

        :param text_person_name_annotations: The text_person_name_annotations of this TextPersonNameAnnotationResponse.
        :type text_person_name_annotations: List[TextPersonNameAnnotation]
        """
        if text_person_name_annotations is None:
            raise ValueError("Invalid value for `text_person_name_annotations`, must not be `None`")  # noqa: E501

        self._text_person_name_annotations = text_person_name_annotations
