# coding: utf-8

from __future__ import absolute_import
from openapi_server.models.base_model_ import Model
from openapi_server.models.note import Note
from openapi_server import util


class TextPersonNameAnnotationRequest(Model):
    """NOTE: This class is auto generated by
    OpenAPI Generator (https://openapi-generator.tech).
    Do not edit the class manually.
    """

    def __init__(self, note=None):  # noqa: E501
        """TextPersonNameAnnotationRequest - a model defined in OpenAPI

        :param note: The note of this TextPersonNameAnnotationRequest.  # noqa: E501
        :type note: Note
        """
        self.openapi_types = {
            'note': Note
        }

        self.attribute_map = {
            'note': 'note'
        }

        self._note = note

    @classmethod
    def from_dict(cls, dikt) -> 'TextPersonNameAnnotationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextPersonNameAnnotationRequest of this TextPersonNameAnnotationRequest.  # noqa: E501
        :rtype: TextPersonNameAnnotationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note(self):
        """Gets the note of this TextPersonNameAnnotationRequest.


        :return: The note of this TextPersonNameAnnotationRequest.
        :rtype: Note
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this TextPersonNameAnnotationRequest.


        :param note: The note of this TextPersonNameAnnotationRequest.
        :type note: Note
        """
        if note is None:
            raise ValueError("Invalid value for `note`, must not be `None`")  # noqa: E501

        self._note = note
